FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        curl \
        jq \
        mosquitto-clients \
        procps \
        python3 \
        python3-serial \
    && rm -rf /var/lib/apt/lists/*

ADD sources/ /opt/
ADD config/ /etc/inverter/

HEALTHCHECK \
    --interval=30s \
    --timeout=10s \
    --start-period=1m \
    --retries=3 \
  CMD /opt/healthcheck

WORKDIR /opt
ENTRYPOINT ["/bin/bash", "/opt/inverter-mqtt/entrypoint.sh"]
