version: '3'

services:
  marsriva-mqtt:

    # Build locally from Dockerfile.dev
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: marsriva-mqtt

    privileged: true
    restart: always

    volumes:
        - ./config/:/etc/inverter/

    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm

  # Used to auto-update images when new versions are released
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower

    restart: always
    privileged: true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command: --interval 500
